teams = {
    'https://www.mackolik.com/takim/alanyaspor/kadro/84fpe0iynjdghwysyo5tizdkk/s%C3%BCper-lig/2020-2021/': (3, 1),  # Alanya
    'https://www.mackolik.com/takim/sivasspor/kadro/f432akygffyamal3h6poig65t/s%C3%BCper-lig/2020-2021/': (1, 0),  # Sivas
    'https://www.mackolik.com/takim/karag%C3%BCmr%C3%BCk/kadro/c3txoz57mu7w9y1jprvnv2flr/s%C3%BCper-lig/2020-2021/': (None, None),  # Karagumruk
    'https://www.mackolik.com/takim/gen%C3%A7lerbirli%C4%9Fi/kadro/embqktr41hfzczc8uav1scmcn/s%C3%BCper-lig/2020-2021/': (None, None),  # Gencler
    'https://www.mackolik.com/takim/fenerbah%C3%A7e/kadro/8lroq0cbhdxj8124qtxwrhvmm/s%C3%BCper-lig/2020-2021/': (None, None),  # Fenerbahce
    'https://www.mackolik.com/takim/denizlispor/kadro/atzw1r6gsxsegd0omo1f0yxkl/s%C3%BCper-lig/2020-2021/': (0, 1),  # Denizli
    'https://www.mackolik.com/takim/gaziantep-fk/kadro/2agzb2h4ppg7lfz9hn7eg1rqo/s%C3%BCper-lig/2020-2021/': (1, 0),  # Gaziantep
    'https://www.mackolik.com/takim/be%C5%9Fikta%C5%9F/kadro/2ez9cvam9lp9jyhng3eh3znb4/s%C3%BCper-lig/2020-2021/': (None, None),  # Besiktas
    'https://www.mackolik.com/takim/istanbul-ba%C5%9Fak%C5%9Fehir/kadro/47njg6cmlx5q3fvdsupd2n6qu/s%C3%BCper-lig/2020-2021/': (1, 3),  # Basaksehir
    'https://www.mackolik.com/takim/hatayspor/kadro/efy1nhpn5l6hc27znhsptegba/s%C3%BCper-lig/2020-2021/': (2, 0),  # Hatay
    'https://www.mackolik.com/takim/%C3%A7aykur-rizespor/kadro/1lbrlj3uu8wi2h9j79snuoae4/s%C3%BCper-lig/2020-2021/': (None, None),  # Rize
    'https://www.mackolik.com/takim/g%C3%B6ztepe/kadro/cjbaf8s09qoa1n11r33gc560x/s%C3%BCper-lig/2020-2021/': (None, None),  # Goztepe
    'https://www.mackolik.com/takim/mke-ankarag%C3%BCc%C3%BC/kadro/a7jkz1m32wntcvegrwjbr85t5/s%C3%BCper-lig/2020-2021/': (1, 0),  # Ankara
    'https://www.mackolik.com/takim/konyaspor/kadro/cw4lbdzlqqdvbkdkz00c9ye49/s%C3%BCper-lig/2020-2021/': (0, 2),  # Konya
    'https://www.mackolik.com/takim/kas%C4%B1mpa%C5%9Fa/kadro/4idg23egrrvtrbgrg7p5x7bwf/s%C3%BCper-lig/2020-2021/': (None, None),  # Kasimpasa
    'https://www.mackolik.com/takim/antalyaspor/kadro/9irsyv431fpuqhqtfq9iwxf2u/s%C3%BCper-lig/2020-2021/': (0, 3),  # Antalya
    'https://www.mackolik.com/takim/trabzonspor/kadro/2yab38jdfl0gk2tei1mq40o06/s%C3%BCper-lig/2020-2021/': (None, None),  # Trabzon
    'https://www.mackolik.com/takim/bb-erzurumspor/kadro/ea2gyhkv6vwmxbxevdb4u3796/s%C3%BCper-lig/2020-2021/': (0, 1),  # Erzurum
    'https://www.mackolik.com/takim/galatasaray/kadro/esa748l653sss1wurz5ps3228/s%C3%BCper-lig/2020-2021/': (3, 0),  # Galatasaray
    'https://www.mackolik.com/takim/kayserispor/kadro/c8ns6z3u8kxldv1zh1evu10rv/s%C3%BCper-lig/2020-2021/': (None, None),  # Kayseri
    'https://www.mackolik.com/takim/yeni-malatyaspor/kadro/du1e3xdbp2q5z7jy31o0vt6t6/s%C3%BCper-lig/2020-2021/': (0, 1)  # Malatya
}

positions = {

    # ALANYASPOR
    'Jose Carlos Coentrao Marafona': 'gk',
    'Ahmet Çağrı Güney': '-',
    'Ufuk Ceylan': '-',
    'Juan Francisco Moreno Fuertes': 'd',
    'Steven Caulker': 'd',
    'Alpay Çelebi': '-',
    'Ahmet Gülay': '-',
    'Fatih Aksoy': '-',
    'Jacques François Moubandje': 'd',
    'Georgios Tzavellas': 'd',
    'Ceyhun Gülselam': '-',
    'Tayfur Bingöl': '-',
    'Alperen Soysal': '-',
    'Umut Güneş': '-',
    'Yusuf Özdemir': '-',
    'Kazım Yakmaz': '-',
    'Emmanouil Siopis': 'm',
    'Ümit Türker': '-',
    'Fırat Çakıroğlu': '-',
    'Berkan İsmail Kutlu': '-',
    'Efecan Karaca': 'm',
    'Salih Uçan': 'm',
    'Efkan Bekiroglu': '-',
    'Hasan Ayaroğlu': '-',
    'Davidson da Luz Pereira': 'm',
    'Khouma El Hadji Babacar': 'st',
    'Anastasios Bakasetas': ('m', 2),
    'Adam Fernando Bareiro Gamarra': '-',
    'Mustafa Pektemek': '-',

    # SIVASSPOR
    'Mamadou Samassa': 'gk',
    'Ali Şaşal Vural': '-',
    'Baver Kuçkar': '-',
    'Muammer Yıldırım': '-',
    'Ziya Erdal': '-',
    'Marcelo Augusto Ferreira Teixeira': 'd',
    'Barış Yardımcı': '-',
    'Mikail Balkaya': '-',
    'Samba Camara': '-',
    'Aaron Appindangoye': 'd',
    'Uğur Çiftçi': 'd',
    'Caner Osmanpaşa': 'd',
    'Isaac Cofie': '-',
    'Armin Đerlek': '-',
    'Kerem Atakan Kesgin': '-',
    'Claudemir Domingues de Souza': 'm',
    'Hakan Arslan': '-',
    'Serhiy Rybalka': '-',
    'Robin Yalçın': 'm',
    'Erdoğan Yeşilyurt': 'm',
    'Fayçal Fajr': 'm',
    'Samet Kılıçkaya': '-',
    'Kubilay Eren Şahin': '-',
    'Yasin Öztekin': '-',
    'Jorge Félix Muñoz García': '-',
    'Olarenwaju Kayode': '-',
    'Max-Alain Gradel': 'm',
    'Safa Gundak': '-',
    'Arouna Koné': '-',
    'Mustapha Yatabaré': 'st',
    'Rodrigue Casimir Ninga': '-',

    # KARAGUMRUK
    'Muzaffer Cem Kablan': '-',
    'Aykut Özer': '-',
    'Emiliano Viviano': 'gk',
    'Yavuz Ulaş Genç': '-',
    'Enzo Roco': '-',
    'Ervin Zukanović': '-',
    'Jure Balkovec': 'd',
    'Fatih Kuruçuk': 'd',
    'Murat Sarıgül': '-',
    'Koray Altınay': '-',
    'Alparslan Erdem': 'd',
    'Furkan Kara': '-',
    'Ali Sarı': '-',
    'Eric Lichaj': '-',
    "Papa Alioune N'Diaye": 'm',
    'Zeki Yıldırım': 'm',
    'Lucas Rodrigo Biglia': ('m', 1),
    'Muhammed Egemen Pehlivan': '-',
    'Aksel Aktaş': '-',
    'Aatif Chahechouhe': 'm',
    'Alassane Ndao': 'm',
    'Jimmy Durmaz': '-',
    'Ramazan Civelek': 'm',
    'Yusuf Erdoğan KARAGUMRUK': '-',
    'Erik Sabo': ('-', 2),
    'Efe Tatlı': '-',
    'Vato Arveladze': '-',
    'Mevlüt Erdinç': 'st',
    'Artur Sobiech': '-',
    'Brahim Darri': '-',
    'Yannis Salibur': '-',

    # GENCLERBIRLIGI
    'Atalay Gökce': '-',
    'Kristoffer Nordfeldt': 'gk',
    'Übeyd Adıyaman': '-',
    'Diego Ângelo de Oliveira': '-',
    'Pierre-Yves Polomat': 'd',
    'Mattias Johansson': '-',
    'Arda Kızıldağ': 'd',
    'Salih Dursun': '-',
    'Zargo Touré': '-',
    'Abdullah Şahindere': '-',
    'Kadir Enes Kıra': '-',
    'Ömürcan Artan': 'd',
    'Halil İbrahim Pehlivan': '-',
    'Rahmetullah Berişbek': '-',
    'Murat Yıldırım': 'm',
    'Mustafa Hüseyin Seyhan': '-',
    'Berat Özdemir': 'm',
    'Dominik Furman': '-',
    'Daniel João Santos Candeias': 'm',
    'Mustafa Çeçenoğlu': '-',
    'Soner Dikmen': '-',
    'Sefa Yılmaz': 'm',
    'Robert Ayrton Piris Da Motta': 'm',
    'Baran Başyiğit': '-',
    'Bogdan Stancu': 'st',
    'Giovanni-Guy Yann Sio': 'st',
    'Floyd Ayité': '-',
    'İlker Karakaş': '-',
    'Sami Gökhan Altıparmak': '-',

    # FENERBAHCE
    'Altay Bayındır': '-',
    'Bartu Kulbílge': '-',
    'Harun Tekin': '-',
    'Oytun Özdoğan': '-',
    'Marcel Tisserand': '-',
    'Sadık Çiftpınar': '-',
    'Mikael Askarov': '-',
    'Serdar Aziz': '-',
    'Gökhan Gönül': '-',
    'Gürkan Başkan': '-',
    'Nazim Sangare': '-',
    'Filip Novák': '-',
    'Mauricio Lemos Merladet': '-',
    'Caner Erkin': '-',
    'Ferdi Kadıoğlu': '-',
    'Arda Guler': '-',
    'Ömer Faruk Beyaz': '-',
    'Uğur Kaan Yıldız': '-',
    'Nabil Dirar': '-',
    'Serhat Ahmetoğlu': '-',
    'Ozan Tufan': ('-', 1),
    'Dimitris Pelkas': '-',
    'Diego Perotti': ('-', 2),
    'Fatih Mert Çırtlık': '-',
    'Tolga Ciğerci': '-',
    'José Sosa': ('-', 2),
    'Eyüp Akcan': '-',
    'Luiz Gustavo Dias': '-',
    'Mert Hakan Yandaş': '-',
    'Gülhan Üreyen': '-',
    'Enner Remberto Valencia Lastra': '-',
    'Mbwana Ally Samatta': '-',
    'Sinan Gümüş': '-',
    'Mame Thiam': '-',
    'Kemal Ademi': '-',
    'Papiss Cissé': '-',

    # DENIZLISPOR
    'Ali Eren Yalçın': '-',
    'Hüseyin Altıntaş': '-',
    'Cenk Gönen': '-',
    'Costel Fane Pantilimon': 'gk',
    'Abdülkadir Sünger': '-',
    'Zakarya Bergdich': 'd',
    'Sakıb Aytaç': '-',
    'Neven Subotić': '-',
    'Fabiano Leismann': 'd',
    'Tiago Lopes': 'd',
    'Emirhan Kaşcıoğlu': '-',
    'Mustafa Yumlu': 'd',
    'Özgür Çek': '-',
    'Oğuz Yılmaz': '-',
    'Özer Özdemir': '-',
    'Muhammet Özkal': '-',
    'Mert Sarıkuş': '-',
    'Ismail Aissati': 'm',
    'Mathieu Cangni Dossevi': '-',
    'Furkan Şahin': '-',
    'Federico Nicolás Varela': '-',
    'Marvin Bakalorz': 'm',
    'Recep Niyaz': 'm',
    'Radosław Murawski': ('m', 1),
    'Muhammed Eren Kiryolcu': '-',
    'Ángelo Nicolás Sagal Tapia': '-',
    'Alihan Kalkan': '-',
    'Hugo Rodallega': ('st', 1),
    'Hadi Sacko': 'm',
    'Muris Mešanović': '-',

    # GAZIANTEP
    'Mustafa Burak Bozan': '-',
    'Çağlar Akbaba': '-',
    'Günay Güvenç': 'gk',
    'Paweł Olkowski': 'd',
    'Alin Dorinel Toșca': 'd',
    'Ulaş Zengin': '-',
    'Jean-Armel Kana-Biyik': 'd',
    'Papiss Djilobodji': 'd',
    'Iraneuton Sousa Morais Junior': '-',
    'Erdem Uğurlu': '-',
    'Oğuz Ceylan': '-',
    'André Alexandre Carreira Sousa': '-',
    'Güray Vural': 'm',
    'Abdul Aziz Tetteh': '-',
    'Amedej Vetrih': 'm',
    'Jefferson Nogueira Junior': '-',
    'Kubilay Aktaş': '-',
    'Zvonimir Kožulj': 'm',
    'Kenan Özer': 'm',
    'Alexandru Iulian Maxim': ('-', 5),
    'Enver Cenk Şahin': '-',
    'Kevin Mirallas': 'm',
    'Ali Ateş': '-',
    'Furkan Soyalp': '-',
    'Mirza Cihan': '-',
    'Ökkeş Karaoğlu': '-',
    'Muhammet Demir': '-',
    'André Felipe Ribeiro de Souza': '-',
    'Nouha Dicko': 'st',
    'Mehmet Salih Yiğit': '-',

    # BESIKTAS
    'Utku Yuvakuran': '-',
    'Ersin Destanoğlu': 'gk',
    'Emre Bilgin': '-',
    'Rıdvan Yılmaz': 'd',
    'Valentin Rosier': 'd',
    'Welinton Souza Silva': 'd',
    "Fabrice N'Sakala": '-',
    'Erdoğan Kaya': '-',
    'Serdar Saatçı': '-',
    'Douglas Pereira dos Santos': '-',
    'Nicolas Isimat-Mirin': '-',
    'Francisco Javier Montero Rubio': '-',
    'Domagoj Vida': 'd',
    'Kartal Kayra Yılmaz': '-',
    'Gökhan Töre': '-',
    'Dorukhan Toköz': '-',
    'Atiba Hutchinson': 'm',
    'Adem Ljajić': '-',
    'Rachid Ghezzal': 'm',
    'Bernard Mensah': ('m', 1),
    "Georges-Kevin N'Koudou Mbida": '-',
    'Oğuzhan Özyakup': '-',
    'Necip Uysal': '-',
    'Almos Kaan Kalafat': '-',
    'Jeremain Lens': '-',
    'Josef de Souza Dias': 'm',
    'Emirhan Delibal': '-',
    'Cyle Larin': 'st',
    'Güven Yalçın': '-',
    'Ajdin Hasić': '-',
    'Vincent Paté Aboubakar': ('st', 4),
    'Hüseyin Atakan Üner': '-',
    'Tyler Boyd': '-',

    # BASAKSEHIR
    'Muhammed Şengezer': '-',
    'Deniz Dilmen': '-',
    'Volkan Babacan': 'gk',
    'Ahmet Said Kıvanç': '-',
    'Mert Günok': '-',
    'Muhammed Emin Sarıkaya': '-',
    'Uğur Uçar': '-',
    'Boli Bolingoli-Mbombo': '-',
    'Uilson de Souza Paula Júnior': '-',
    'Emre Kaplan': '-',
    'Cemali Sertel': 'd',
    'Hasan Ali Kaldırım': '-',
    'Carlos dos Santos Rodrigues': 'd',
    'Ravil Tagir': '-',
    'Alexandru Epureanu': 'd',
    'Rafael Pereira da Silva': 'd',
    'Martin Škrtel': '-',
    'Nacer Chadli': 'm',
    'Giuliano Victor de Paula': '-',
    'Mehmet Topal': '-',
    'Mete Kaan Demir': '-',
    'Azubuike Okechukwu': '-',
    'Deniz Türüç': '-',
    'Danijel Aleksić': 'm',
    'Mahmut Tekdemir': 'm',
    'Kerim Frei': '-',
    'Serhan Üresin': '-',
    'İrfan Can Kahveci': 'm',
    'Edin Višća': ('m', 1),
    'Yunus Emre Baloğlu': '-',
    'Berkay Özcan': '-',
    'Enes Karakuş': '-',
    'Enzo Crivelli': '-',
    'Fredrik Gulbrandsen': 'st',
    'Demba Ba': '-',

    # HATAYSPOR
    'Akın Alkan': '-',
    'Yavuz Buğra Boyar': '-',
    'Munir Mohand Mohamedi': 'gk',
    'Mesut Çaytemel': '-',
    'Jean-Claude Billong': 'd',
    'Yusuf Abdioğlu': '-',
    'Soner Örnek': '-',
    'Melih Aşkar': '-',
    'Pablo Renan dos Santos': 'd',
    'Abdurrahman Canlı': '-',
    'Strahil Popov': 'd',
    'Baha Berk Aygün': '-',
    'Alexandros Katranis': 'd',
    'Isaac Sackey': '-',
    'Gökhan Karadeniz': '-',
    'Joseph Akomadi': '-',
    'Adama "Noss" Traoré': 'm',
    'Babajide David Akintola': 'm',
    'Hélder Barbosa': '-',
    'Selim Ilgaz': '-',
    'Burak Can Çamoglu': '-',
    'Rayane Aabid': 'm',
    'Mert Altınöz': '-',
    'Rúben Tiago Rodrigues Ribeiro': 'm',
    'Mame Biram Diouf': ('st', 1),
    'Aaron Salem Boupendza Pozzi': 'st',
    'Mirkan Aydın': '-',
    'Idir Ouali': '-',
    'Dame Diop': '-',

    # RIZESPOR
    'Gökhan Akkan': 'gk',
    'Tarık Çetin': '-',
    'Boğaçhan Kazmaz': '-',
    'Zafer Görgen': '-',
    'Selim Ay': '-',
    'Yassine Meriah': 'd',
    'Dimitris Chatziisaias': '-',
    'İsmail Köybaşı': 'd',
    'Montassar Talbi': 'd',
    'Dario Melnjak': '-',
    'Murat Sağlam': '-',
    'Mykola Moroziuk': 'd',
    'Emir Dilaver': '-',
    'Alberk Koç': '-',
    'Emir Han Topçu': '-',
    'Fabricio Santos de Jesus': '-',
    'Konrad Michalak': 'm',
    'Emrecan Uzunsakal': '-',
    'Abdullah Durak': '-',
    'Mithat Pala': '-',
    'Yasin Pehlivan': 'm',
    'Ismaël Tiémoko Diomandé': '-',
    'Tunay Torun': 'm',
    'Doğan Erdoğan': '-',
    'Fernando Boldrin': ('-', 1),
    'Dušan Jovančić': '-',
    'Godfred Donsah': 'm',
    'Serdar Köse': '-',
    'Onur Bulut': '-',
    'Aminu Umar': '-',
    'Muharrem Bostancı': '-',
    'Milan Škoda': ('st', 1),
    'Fernando Andrade dos Santos': 'm',
    'Loïc Rémy': ('-', 2),
    'Braian José Samudio Segovia': '-',
    'Kemal Rüzgar': '-',

    # GOZTEPE
    'Balázs Megyeri': 'gk',
    'İrfan Can Eğribayat': '-',
    'Arda Özçimen': '-',
    'Atınç Nukan': 'd',
    'Murat Paluli': 'd',
    'Cristian Chagas Tarouco': '-',
    'Berkan Emir': '-',
    'Marko Mihojević': 'd',
    'Dženan Bureković': 'd',
    'Lamine Gassama': '-',
    'Halil Akbunar': 'm',
    'Soner Aydoğdu': 'm',
    'José Márcio da Costa': '-',
    'Yılmaz Basravi': '-',
    'Burak Süleyman': '-',
    'André Biyogo Poko': '-',
    'Efe Binici': '-',
    'Metin Yıldırım': '-',
    'Alpaslan Öztürk': ('-', 1),
    'Guilherme Costa Marques': ('-', 1),
    'Yalçın Kayan': 'm',
    'Zlatko Tripić': 'm',
    'Kubilay Sönmez': '-',
    'Obinna Nwobodo': 'm',
    'Batuhan Kırdaroğlu': '-',
    'Stefano Napoleoni': '-',
    'Brown Ideye Aide': '-',
    'Pape Cherif Ndiaye': 'st',

    # ANKARAGUCU
    'Mert Topuz': '-',
    'Furkan Bekleviç': '-',
    'Korcan Çelikay': '-',
    'Ricardo Henrique Schuck Friedrich': 'gk',
    'Yusuf Göktas': '-',
    'Atila Turan': '-',
    'Idriz Naser Voca': 'm',
    'Zvonimir Šarlija': 'd',
    'Stelios Kitsiou': 'd',
    'Erdi Dikmen': '-',
    'Tiago Pinto': 'd',
    'Cebrail Karayel': '-',
    'Murat Sipahioğlu': '-',
    'Anıl Dikmen': '-',
    'Ante Kulusic': '-',
    'Michał Pazdan': '-',
    'Atakan Rıdvan Çankaya': 'd',
    'Endri Çekiçi': 'm',
    'Luka Adžić': '-',
    'Mehmet Ali Akın': '-',
    'Daniel Łukasik': 'm',
    'Şahverdi Çetin': '-',
    'Ender Aygören': '-',
    'Orkan Çınar': '-',
    'Saba Lobzhanidze': 'm',
    'Alper Potuk': '-',
    'Assane Dioussé El Hadji': '-',
    'Joseph Martin Paintsil': 'm',
    'Torgeir Børven': ('-', 1),
    'Emre Güral': ('-', 1),
    'Mücahit Can Akçay': '-',
    'Jonathan Bolingi Mpangi Merikani': 'st',
    'Berke Gürbüz': '-',

    # KONYASPOR
    'Erten Ersu': '-',
    'Eray Birniçan': '-',
    'Ibrahim Šehić': 'gk',
    'Serkan Kırıntılı': '-',
    'Ozan Can Oruç': '-',
    'Guilherme Haubert Sitya': 'd',
    'Uğur Demirok': ('-', 3),
    'Alper Uludağ': '-',
    'Abdülkerim Bardakcı': 'd',
    'Ahmet Çalık': 'd',
    'Nejc Skubic': 'd',
    'Marin Aničić': '-',
    'Adil Demirbağ': 'd',
    'Levan Shengelia': '-',
    'Deni Milosevic': 'm',
    'Mücahit Kaya': '-',
    'Oğuzhan Eskiköy': '-',
    'Şener Kaya': '-',
    'Christopher Paolo César Hurtado Huertas': '-',
    'Ali Karakaya': '-',
    'Samuel Emem Eduok': '-',
    'Emre Pehlivan': '-',
    'İzzet Karaboğa': '-',
    'Ömer Ali Şahiner': '-',
    'Volkan Fındıklı': '-',
    'Marko Jevtović': 'm',
    'Oğuz Kağan Güçtekin': '-',
    'Musa Çağıran': '-',
    'Abdulsamet Kaya': '-',
    'Amir Hadžiahmetović': 'm',
    'Farouk Miya': '-',
    'Sokol Cikalleshi': '-',
    'Erdon Daci': 'st',
    'Artem Kravets': ('st', 1),

    # KASIMPASA
    'Ramazan Köse': '-',
    'Erdem Canpolat': '-',
    'Mehmet Enes Sarı': '-',
    'Ertuğrul Taşkıran': 'gk',
    'Oussama Haddadi': 'd',
    'Mickaël Tirpan': '-',
    'Tomáš Břečka': 'd',
    'Julian Jeanvier': '-',
    'Ahmet Oğuz': '-',
    'Evren Eren Elmalı': '-',
    'Florent Hadërgjonaj': 'd',
    'Mehmet Feyzi Yıldırım': '-',
    'Çağtay Kurukalıp': '-',
    'Dogucan Haspolat': '-',
    'Azad Toptik': '-',
    'Alan Lima Cariús': '-',
    'Tarkan Serbest': 'm',
    'Haris Hajradinović': 'm',
    'Aytaç Kara': 'm',
    'Loret Sadiku': 'm',
    'Kevin Varga': 'm',
    'Anıl Koç': '-',
    'Yusuf Erdoğan KASIMPASA': 'm',
    'Bengali-Fodé Koita': '-',
    'Gerard Bi Goua Gohou': '-',
    'Yasin Dülger': '-',
    'Armin Hodžić': 'st',
    'Gilbert Koomson': '-',

    # ANTALYASPOR
    'Ruud Boffin': 'gk',
    'Ferhat Kaplan': '-',
    'Doğukan Özkan': '-',
    'Bünyamin Balcı': 'd',
    'Ersan Adem Gülüm': '-',
    'Ali Eren İyican': '-',
    'Veysel Sarı': 'd',
    'Eren Albayrak': '-',
    'Edinaldo Gomes Pereira': 'd',
    'Mert Yılmaz': '-',
    'Fedor Kudryashov': 'd',
    'Bahadır Öztürk': '-',
    'Serdar Poyraz': '-',
    'Y. Berke Güner': '-',
    'Alfredo Kulembe Ribeiro': 'm',
    'Emircan Uçar': '-',
    'Mevlüt Han Ekelik': '-',
    'Ufuk Akyol': '-',
    'Nuri Şahin': 'm',
    'Doğukan Sinik': '-',
    'Hakan Özmert': '-',
    'Adem Metin Turk': '-',
    'Serdar Gürler': '-',
    'Omar Imeri': '-',
    'Sidney Sam': 'm',
    'Amilton Minervino da Silva': 'm',
    'Lukas Podolski': 'st',
    'Gökdeniz Bayrakdar': '-',
    'Adis Jahović': '-',
    'Dever Orgill': 'st',
    'Jean Armel Drole': '-',

    # TRABZONSPOR
    'Arda Akbulut': '-',
    'Uğurcan Çakır': 'gk',
    'Erce Kardeşler': '-',
    'Muhammet Taha Tepe': '-',
    'Ahmetcan Kaplan': '-',
    'Marlon Rodrigues Xavier': 'd',
    'Vitor Hugo Franchescoli de Souza': 'd',
    'Edgar Miguel Ié': 'd',
    'Hüseyin Türkmen': '-',
    'Gastón Campi': '-',
    'Seyed Majid Hosseini': '-',
    'Serkan Asan': 'd',
    'Kamil Ahmet Çörekçi': '-',
    'João Pereira': '-',
    'Atakan Gündüz': '-',
    'Faruk Can Genç': '-',
    'Kerem Baykuş': '-',
    'Abdülkadir Ömür': '-',
    'Lewis Baker': 'm',
    'Abdulkadir Parmak': 'm',
    'Safa Kınalı': '-',
    'Anders Trondsen': '-',
    'Flavio Medeiros da Silva': 'm',
    'Taha Tunç': '-',
    'Ahmet Canbaz': '-',
    'Süleyman Cebeci': '-',
    'Stiven Ricardo Plaza Castillo': '-',
    'Jorge Djaniny Tavares Semedo': 'st',
    'Fousseni Diabaté': '-',
    'Salih Kavrazlı': '-',
    'Caleb Ekuban': ('st', 1),
    'Bilal Başacıkoğlu': '-',
    'Benik Afobe': '-',
    'Anthony Nwakaeme': 'm',
    'Yusuf Sarı': '-',

    # ERZURUMSPOR
    'Fabien Farnolle': 'gk',
    'Kayacan Erdoğan': '-',
    'Batuhan Ünsal': '-',
    'Léo Schwechlen': 'd',
    'Haluk Hakan Baydan': '-',
    'Mucahit Albayrak': '-',
    'Hasan Hatipoğlu': '-',
    'Adolphe Teikeu Kamgang': 'd',
    'Fırat Şaşi': '-',
    'Arturo Mina': '-',
    'Cenk Ahmet Alkılıç': 'd',
    'Gökhan Kardeş': '-',
    'Kaan Kanak': '-',
    'Jugurtha Hamroun': '-',
    'Ibrahim Sissoko': '-',
    'Petrus Boumal Mayega': 'm',
    'Yusuf Koç': '-',
    'Arvydas Novikovas': ('m', 2),
    'Emrah Başsan': 'm',
    'İbrahim Akdağ': '-',
    'Osman Çelik': 'd',
    'Murat Uçar': '-',
    'Mitchell Glenn Donald': 'm',
    'Gabriel Obertan': 'm',
    'Serdar Yıldırım': '-',
    'Ömer Hasan Şişmanoğlu': '-',
    'Ricardo Jorge Pires Gomes': 'st',
    'Armando Sadiku': '-',
    'Rashad Muhammed': '-',
    'Oltan Karakullukçu': '-',

    # GALATASARAY
    'Fernando Muslera': '-',
    'Fatih Öztürk': '-',
    'Okan Kocuk': 'gk',
    'Valentine Ozornwafor': '-',
    'Marcos Teixeira': 'd',
    'Işık Kaan Arslan': '-',
    'Emin Bayram': '-',
    'Ömer Bayram': '-',
    'Martin Linnes': '-',
    'Omar Elabdellaoui': 'd',
    'Marcelo Josemir Saracchi Pintos': 'd',
    'Christian Luyindama': 'd',
    'Emre Taşdemir': '-',
    'Şener Özbayraklı': '-',
    'Oghenekaro Etebo': '-',
    'Muhammed Kerem Aktürkoğlu': '-',
    'Emre Akbaba': '-',
    'Mustafa Fettahoğlu': '-',
    'Younès Belhanda': 'm',
    'Ryan Donk': 'd',
    'Sofiane Feghouli': '-',
    'Emre Kılınç': 'm',
    'Taylan Antalyalı': '-',
    'Arda Turan': 'm',
    'Ali Yavuz Kol': '-',
    'Oğulcan Çağlayan': 'm',
    'Ryan Babel': '-',
    'Mbaye Diagne': ('-', 3),
    'Radamel Falcao García Zárate': ('st', 3),
    'Jesse Tamunobaraboye Sekidika': '-',

    # KAYSERISPOR
    'Doğan Alemdar': '-',
    'Abdulkadir Taşdan': '-',
    'Silviu Lung': '-',
    'İsmail Çipe': 'gk',
    'Aziz Behich': 'd',
    'Barış Emirhan Doğan': '-',
    'Cristian Săpunaru': 'd',
    'Dimitrios Kolovetsios': '-',
    'Oğuzhan Çapar': 'd',
    'Miguel Lopes': 'd',
    'Yasir Subaşı': '-',
    'Adem Doğan': '-',
    'Muhammed Eren Arıkan': '-',
    'Joseph Attamah': 'd',
    'Nurettin Korkmaz': '-',
    'Daniel Avramovski': '-',
    'İlhan Depe': '-',
    'Gustavo Campanharo': 'm',
    'Talha Sarıarslan': '-',
    'Ahmet Zekeriyya Kartal': '-',
    'Pedro Henrique': ('m', 2),
    'Yaw Ackah': '-',
    'Mehmet Eray Özbek': '-',
    'Zoran Kvržić': 'm',
    'Manuel Henrique Tavares Fernandes': '-',
    'Hasan Hüseyin Acar': '-',
    'Aaron Lennon': '-',
    'Denis Alibec': '-',
    'Muğdat Çelik': '-',
    'İlhan Parlak': '-',
    'Ömer Uzun': '-',
    'Harrisson Manzala Tusumgama': 'm',
    'Aka Wilfried Kanga': 'st',
    'Emre Demir': '-',
    'Okan Acar': '-',

    # MALATYASPOR
    'Guido Herrera': '-',
    'Ertaç Özbir': 'gk',
    'Murat Akşit': '-',
    'Eray İşcan': '-',
    'Abdulsamed Damlu': '-',
    'Issam Chebake': 'd',
    'Bülent Cevahir': '-',
    'Erşan Yaşa': '-',
    'Erkan Kaş': '-',
    'Karim Hafez': 'd',
    'Mustafa Akbaş': '-',
    'Zeki Yavru': '-',
    'Murat Akça': '-',
    'Semih Kaya': 'd',
    'Teenage Lingani Hadebe': 'd',
    'Wallace Fortuna dos Santos': '-',
    'Ahmed Ildız': 'm',
    'Christian Alberto Cueva Bravo': '-',
    'Fernando Zuqui': '-',
    'Olcay Şahan': '-',
    'Mustafa Eskihellaç': '-',
    'Youssouf Ndayishimiye': 'm',
    'Berk Yıldız': '-',
    'Doğukan Emeksiz': '-',
    'Afriyie Acquah': '-',
    'Kubilay Kanatsızkuş': 'st',
    'Benjamin Tetteh': 'st',
    'Jetmir Topalli': '-',
    'Moryké Fofana': 'm',
    'Jody Lukoki': '-',
    'Umut Bulut': 'st',
    'Adem Büyük': ('-', 5),
}
